### ISSUE TITLE
Use webpack-dev-middleware to hold bundles in memory

### ISSUE THREAD

**Issue by mover96** [DavideViolante/Angular2-Express-Mongoose#2]
Hey there, I am trying to implement this project, but I want my bundles to be in memory so that the rebundles are a lot faster and I can use HMR. Any suggestions on how to add the functionality to the express server to handle this with webpack-dev-middleware? I will spend some time on it this weekend and submit a PR if I can get it all working.

**Comment by DavideViolante** [comment]
I almost have no idea on what you are talking about, sorry. Can you provide me a link with more info or an example?
Btw keep in mind that this project has the goal to be as simple as possible, so I'm not going to add rare/hard features (even if they are good).
