### ISSUE TITLE
Update needed

### ISSUE THREAD

**Issue by zeeeqy** [DavideViolante/Angular2-Express-Mongoose#4]
Everything works however the outdated form form module error, please see below.

*It looks like you're using the old forms module. This will be opt-in in the next RC, and
      will eventually be removed in favor of the new forms module. For more information, see:
https://docs.google.com/document/u/1/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub

**Comment by DavideViolante** [comment]
Yes, I know. I will update the forms when the Angular forms are more stable.
