### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by hanson0291** [DavideViolante/Angular2-Express-Mongoose#5]
I have the database and the server up, but the client keeps saying "Loading", why doesn't it update?  I also don't understand my uncaught syntax error..  help please?  Does it have something to do with the application using typescript?

![screen shot 2016-08-07 at 9 14 40 pm](https://cloud.githubusercontent.com/assets/8506569/17466780/2a363b68-5ce4-11e6-81f2-e2986e8dd355.png)

**Comment by DavideViolante** [comment]
Are you sure you installed all the dependencies? I don't see the node_modules folder.
You have to do "npm install" and wait that all deps are installed, then "npm start" (and before them "mongod" in another command window). Also you don't have to create the folder scripts into public folder. They are "virtual links" handled by express.js. The real path of these are from node_modules. (see server.js file line 9)

**Comment by zeeeqy** [comment]
I agree with DavideViolante however would like to add to his solution...

First: clone or fork a clean copy of the project, CD to the folder and run

`npm install`

once the dependencies are installed, make sure you have all the latest version e.g. Node, Express and Mongodb which I presume you do.

Before you run npm start, make sure to start mongodb server listening on port No. 27017, just run mongod in there terminal.

If doesn't work, please post your console error.
