### ISSUE TITLE
mongo update cat error

### ISSUE THREAD

**Issue by developerJordy** [DavideViolante/Angular2-Express-Mongoose#6]
When I try to update a cat I get this mongo error:

[1]   name: 'MongoError',
[1]   message: 'exception: Mod on _id not allowed',
[1]   value: 
[1]    { name: 'cat1',
[1]      age: 5,
[1]      weight: 2,
[1]      _id: 57b30f94b642ee7a18ab5c42,
[1]      __v: 0 },
[1]   errmsg: 'exception: Mod on _id not allowed',
[1]   code: 10148,
[1]   ok: 0 }

 (even after pulling a fresh copy of the repo). Inserting and deleting cats from the mongoDB works great.

**Comment by DavideViolante** [comment]
That's strange, did you edit some lines of my code? I can update the cats without any issue. What version of MongoDB and Node you have? Did you create the "cats" database by yourself (it should be created automatically) or you add any index? Does you receive any error in browser console too (F12 in Chrome)? Check also the "Network" tab (I'm using Chrome: F12 -> Network) while you edit the cat and tell me what you see there. There should be a successful PUT request (the edit) with the new data.

**Comment by developerJordy** [comment]
I was making changes in the code, but now the problem persists after pulling fresh copy's of the repo without code changes. I have not created any databases myself. 
I get no console errors and the network call status is 'pending' when I click save after updating.

$ mongod --version
db version v2.4.9

node -v
v6.0.0

I'm starting to suspect that this is an outdated mongo problem.

**Comment by DavideViolante** [comment]
I think you are right, please update MongoDB (I've 3.2.8) and let me know if it persists. Also note that I didn't test it with Node 6.x, I've 4.4.7.

**Comment by developerJordy** [comment]
I have updated mongoDB to 3.2.8 and updating records works again, thanks !

If I may make a suggestion for the app it'd be:
- maybe an auth functionaility (jwt tokens?) for securing the routes with canActivate 
- and an api (secured)  for save data calls

Thanks for the help and for sharing the project. I like its simplicity , ideal for learning MEAN with angular2. Now I'll try to replace mongoDB with mongo lab.

**Comment by DavideViolante** [comment]
Good!
About the suggestions:
- authentication is not a simple task and can be accomplished in multiple ways. I want to keep the project very simple. I don't know if I will add it in future (maybe in a separate project with Angular 2 final). Btw JWT is a good way to do it.
- do you mean secured api calls so that only authorized users can call /api/xxx? If so, yes it should be implemented because now everyone can call update and delete api calls and this is not really cool...
About mLab I think you just need to edit line 18 of server.js, so that you can use a remote mongo database.

**Comment by developerJordy** [comment]
It might indeed be better to wait for the final Angular 2 release and make it a seperate project, and for the API  I mean indeed that only authorized users can make calls so it relies on the authentication. 

And thanks for the mlab tip !
