### ISSUE TITLE
Getting some warnings in the beginning when npm install

### ISSUE THREAD

**Issue by esuarezz** [DavideViolante/Angular2-Express-Mongoose#7]
- npm WARN package.json Dependency 'webpack' exists in both dependencies and devDependencies, using 'webpack@^1.13.2' from dependencies

-npm WARN optional dep failed, continuing fsevents@1.0.14

**Comment by DavideViolante** [comment]
You are right, thanks for the issue. Fixed in latest commit. (Just remove webpack from dependencies and leave it in devDependencies).

**Comment by esuarezz** [comment]
Good job anyway!
