### ISSUE TITLE
I dont see where i can ask questions... so I open this

### ISSUE THREAD

**Issue by esuarezz** [DavideViolante/Angular2-Express-Mongoose#8]
Where would you put the server logic...

So, i see you have introduced everything in server.js .
But if I want to put an API with typescript where would you put? because if we put this in app folder I guess is going to be in the client and we could show too much information...
and of course it is impossible to have an api and more stuff into this server.js file
thanks!

**Comment by DavideViolante** [comment]
The server logic can be written also in TypeScript (you can see this project: https://github.com/angular/universal-starter) and it must be separated from client side app (Angular). Remember that Angular is a front-end framework that can have any language on the backend. I decided to use Express, so you can see server.js file. It is incorrect when you say that "is impossible to have an api and more stuff into server.js". You can always organize the code better and create multiple .js files for the server side. For example the "models" should be in their own files (see latest commit).

**Comment by esuarezz** [comment]
Yes, I was thinking just if i start to put files in another folder if they will be sent to the client or remain in server.. Because I would like to extract that api you have in the server.js

**Comment by DavideViolante** [comment]
Only app and public folder are client side. Node uses server.js file to run its server, so that file and any file that is included or used in server.js will be server side. Note that using Express you can define static paths  and you must be careful to not include server files to static paths (line 8-11), otherwise you can access them via url.

**Comment by esuarezz** [comment]
Thank you davide! now much clear :dart:

**Comment by esuarezz** [comment]
Hi Davide,

Se voglio usare es6, cosa devo fare?

2016-08-25 11:59 GMT+01:00 Davide Violante <notifications@github.com>:

**Comment by go4d1** [comment]
I found your example very helpful. I posted a link to your project here:
https://www.meetup.com/AngularJS-NYC/messages/boards/
Heading Angular2-rc5 Mean Demo  - Please keep up the good work!
